export enum FormFieldType {
    INPUT,
    TEXTAREA,
    CHECKBOX,
    SELECT,
    DATE_PICKER,
    COLOR_PICKER,
    RADIO,
    COMBOBOX,
    QUANTITY_CONTROLLER,
    CHECKBOX_GROUP,
    RADIO_CARD
}